### ISSUE TITLE
global options

### ISSUE THREAD

**Issue by achtan** [storybooks/addon-jsx#21]
hi how to setup global option eg: `{showDefaultProps: false}` ?

**Comment by wcastand** [comment]
Hi you can pass options to `react-element-to-jsx-string` like this : 
```javascript
storiesOf('test 2', module).addWithJSX(
  'Paris',
  () => <TestContainer>Hello there</TestContainer>,
  { showDefaultProps: false },
)
```

options will be passed to `react-element-to-jsx-string`

**Comment by achtan** [comment]
yes, but i need global (default) options, so i dont need to specify `{ showDefaultProps: false }` every time i add new story...

**Comment by dforesman** [comment]
A way to define global options would be ideal - I'm finding that repeating the options in every story is tiresome.

If it would be possible to configure when activating the add-on via `setAddon()`, that would be ideal - users would have the ability to set options per-story, per-file, and for the whole app.

**Comment by Zuurkern** [comment]
How about a decorator that you can use in config.js?
