### ISSUE TITLE
warning.js:33 Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.

### ISSUE THREAD

**Issue by finom** [storybooks/addon-jsx#23]
```
warning.js:33 Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
    in button (created by Title)
    in CopyToClipboard (created by Title)
    in div (created by Title)
    in Title
    in button (created by DownPanel)
    in div (created by DownPanel)
    in div (created by DownPanel)
    in DownPanel (created by Container(DownPanel))
    in Container(DownPanel) (created by Layout)
    in div (created by Layout)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by Layout)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by Layout)
    in div (created by Layout)
    in Layout (created by Container(Layout))
    in Container(Layout)
    in div
```

This happens because of nested `<button>`: 

![image](https://user-images.githubusercontent.com/1082083/32736694-c006b824-c8a0-11e7-8656-297ff6932439.png)

![image](https://user-images.githubusercontent.com/1082083/32736732-d9dabfac-c8a0-11e7-94f6-929f520340a1.png)

**Comment by wcastand** [comment]
Hi,
It's pretty new, since when the title of the tab is a button ?
@ndelangen

**Comment by samouss** [comment]
Hi, the changes occur in the `v3.2.15`. You can check the [PR #2270](https://github.com/storybooks/storybook/pull/2270/files#diff-9512543e459fb3441257267902592fa0R38).

See the full CHANGELOG: https://github.com/storybooks/storybook/releases/tag/v3.2.15

**Comment by samouss** [comment]
Maybe we can move the `Copy` button from the title to the content of the panel? It will fix the issue related to the invalid nested child. The advantages of that is that we will have the control of where the button will be render (no more issue like this one). WDYT?

Happy to help whatever chosen solution 😉

**Comment by wcastand** [comment]
It doesn't really make sense to put the Copy button in the panel since it's not related to the content but i guess we don't really have a choice now that the header is a button itself :)

**Comment by mattcolman** [comment]
I thought nested buttons were ok. Isn't that the point of event propagation? By default you can click both buttons unless you call event.stopPropagation() on the child event?

**Comment by AdnanBoota** [comment]
Any fix for this, i'm also using <ButtonGroup> with "reactstrap": "^6.5.0", and still getting this warning?

Any solution to fix?

Thanks,
Adnan
