### ISSUE TITLE
contributors.md

### ISSUE THREAD

**Issue by Alfredo-Delgado** [storybooks/addon-jsx#28]
I'd like to suggest that a `contributors.md` be added to this project. In particular, I'm interested in how local development should be done.

e.g. I haven't had any luck working around multiple `@storybook/addons` when linking my local addon-jsx repo to my local storybook project.

**Comment by ndelangen** [comment]
I think this: https://github.com/storybooks/addon-jsx/issues/26 would be the correct action to take.

I just haven't gotten around to actually do it. Knowing it will spark a bit of a discussion around duplicate functionality.

Are you already on the Storybook slack? We can discuss this best in the 'addons' channel there, I think. [self invite link](https://now-examples-slackin-rrirkqohko.now.sh/)
