### ISSUE TITLE
Use with TypeScript

### ISSUE THREAD

**Issue by adrice727** [storybooks/addon-jsx#36]
Is there currently a way to use this with `TypeScript`?  I know that there isn't a `@types` package, but I'm wondering if anyone has a declaration file that they're successfully using.  I'm currently getting the error `[ts] Property 'addWithJSX' does not exist on type 'Story'.`

**Comment by adrice727** [comment]
I completely overlooked https://storybook.js.org/configurations/typescript-config/.

**Comment by Braden1996** [comment]
@adrice727, how did you fix that error? Typescript works as expected, by only for the interface `Story` defined in `@types/storybook__react` - it is missing `.addWithJSX(...)`. I can't seem to find anything in the docs about it.

**Comment by bfeeley** [comment]
Same question here ... I'm having the same issue.

**Comment by lecstor** [comment]
I got this working with `(storiesOf("Component", module) as any).addWithJSX()`..
not a real fix, but gets rid of the error..

**Comment by rosskevin** [comment]
The way to do this locally is by setting up module augmentation: https://www.typescriptlang.org/docs/handbook/declaration-merging.html

Here is the content needed in something like `storybook.d.ts`:

```js
import { RenderFunction } from '@storybook/react'

declare module '@storybook/react' {
  export interface Story {
    addWithJSX(storyName: string, callback: RenderFunction): this
  }
}
```

Then you can use it like normal without casting to `any`

**Comment by ndelangen** [comment]
Well actually I'd love for this addon to be migrated away from using the `.addWith...` syntax. It's complicating a lot of things including typescript.

Does anyone here want to help make it happen?

**Comment by timkrins** [comment]
@types has a package now.

`npm install @types/storybook-addon-jsx --save-dev`
