### ISSUE TITLE
Feature request: Allow to configure defaultOpts

### ISSUE THREAD

**Issue by mixail-novikov** [storybooks/addon-jsx#38]
https://github.com/storybooks/addon-jsx/blob/master/src/index.js#L45

I could help with it, if you approve the realization. Below my variant of realization.

Define `let defaultOptions` with current defaults in index.js 
Add exported method, for example `configure`, to index.js.
`cofigure` will receive an argument and simply assign it to the defaultOptions

For future flexibility `configure` may accept object with keys, that define config part.
Like this `configure({jsxOptions: { hereOptions }})`

**Comment by hipstersmoothie** [comment]
I am pretty sure you can do this with `addParameters`. You can use the function globally, in a single file (`stories.addParameter`), or a single story (`add(...., { jsx: { ... }})`)

```js
addParameters({
  jsx: {
    skip: 2
  }
});
```

Does this meet your use case?

**Comment by leepowellcouk** [comment]
I can confirm that this approach works.
