### ISSUE TITLE
flowtype error: Cannot call storiesOf(...).addWithJSX because property addWithJSX is missing in Story

### ISSUE THREAD

**Issue by jasonbarry** [storybooks/addon-jsx#40]
<img width="948" alt="screen shot 2018-05-22 at 2 19 00 pm" src="https://user-images.githubusercontent.com/236451/40390762-1bd11716-5dcb-11e8-8eb2-810287a386da.png">

The `addWithJSX` property is missing from the Story flowtype definition.

**Comment by wuweiweiwu** [comment]
hi @jasonbarry. We currently don't have static types integrated with storybook yet. You get that error because the jsx addon adds the new property via `setAddon`. 

If that is an issue I would use `// $FlowFixMe` which is a flow keyword to suppress errors
