### ISSUE TITLE
The type definition of addWithJSX is missing the third parameter (options) 

### ISSUE THREAD

**Issue by aurerua** [storybooks/addon-jsx#44]
Using in a Typescript project, Typescript complains that addWithJSX can only take two arguments.

The type definition of `addWithJSX` in `@types/storybook-addon-jsx` is missing the third parameter (options).

**Comment by aurerua** [comment]
As a quick temporary workaround one can add a d.ts file to do module augmentation like that:
```js
import '@storybook/react';
import { ReactNode } from 'react';
declare module '@storybook/react' {
    interface Story {
        addWithJSX(kind: string, fn: () => ReactNode, options: object): Story;
    }
}

**Comment by timkrins** [comment]
Typings issues would belong to https://github.com/DefinitelyTyped/DefinitelyTyped

Looks like someone solved it for you:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29071

**Comment by hipstersmoothie** [comment]
Solved via official types package, closing.
