### ISSUE TITLE
storybook v5 support

### ISSUE THREAD

**Issue by wahhapen** [storybooks/addon-jsx#50]
Any plans on updating this addon to work with v5? Tried to add, but it doesn't work.

![image](https://user-images.githubusercontent.com/12165520/53645166-57831b80-3c49-11e9-9a83-d685cd25c06b.png)

**Comment by shilman** [comment]
I plan to supercede this addon in v5.1 so probably won't spend the time to upgrade it. However if somebody wants to do the upgrade, we'd be happy to merge it.

**Comment by hipstersmoothie** [comment]
@shilman any issue i can track about this?

**Comment by shilman** [comment]
@hipstersmoothie Nothing yet. Any interest in collaborating on improving Storybook's documentation features? I'm a fan of `storybook-addon-react-docgen`!

**Comment by eduludi** [comment]
@shilman Hi!

We just migrated one of our libraries to Storybook v5. We really like `addon-jsx` features, so we have some questions:

- What do you mean that you plan to _supercede_ `addon-jsx` in Storybook v5.1?  Does that mean that it's going to be a built-in feature?
- if so, is there some alpha/beta version to do some testing?

We also hope `addon-jsx` don't get discontinued. `storybook-addon-react-docgen` is ok to understand the props. But in Storybook v4, `addon-jsx` offered a really cool feature: you can play around within **Knobs**, and then get the generated code from **JSX**. This is really handy for developers using our UI libraries and their components.

Thanks for your awesome work!

**Comment by hipstersmoothie** [comment]
@eduludi I agree with the usefulness of `addon-jsx`. There probably isn't much work to get this usable for v5. I just haven't been able to work on it

**Comment by eduludi** [comment]
Thank you very much 👍

**Comment by hadnet** [comment]
I installed it but doesn't show up anything in the JSX tab. This is my package.json:

```
{
  "name": "storybook-with-react",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@storybook/addon-info": "^5.1.9",
    "@storybook/addons": "^5.1.9",
    "@storybook/react": "^5.1.9",
    "@babel/core": "^7.4.5",
    "babel-loader": "^8.0.6",
    "storybook-addon-jsx": "^7.1.2"
  },
  "dependencies": {
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "scripts": {
    "storybook": "start-storybook -p 6006 -c .storybook"
  }
} 
```
// .storybook/config.js
```
import {configure, addDecorator} from '@storybook/react';
import addons, { mockChannel } from '@storybook/addons';
import { jsxDecorator } from 'storybook-addon-jsx';

addDecorator(jsxDecorator);

addons.setChannel(mockChannel());

const req = require.context('../src', true, /.stories.js$/);

function loadStories() {
    req.keys().forEach(file => req(file));
}

configure(loadStories, module);
```

// src/Button.js

```
import React from 'react';

export const Button = ({bg, children}) => (<button style={{ backgroundColor: bg}}>{children}</button>);
```


// src/Button.stories.js

```
import React from 'react';
import {withInfo} from '@storybook/addon-info';
import { jsxDecorator } from 'storybook-addon-jsx';
import {storiesOf} from '@storybook/react';
import {Button} from './Button';

storiesOf('Button', module)
    .addDecorator(jsxDecorator)
    .addDecorator(withInfo)
    .add('with bg', () => <Button bg="pink">Hello</Button>);

```
