### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by Superpencil** [storybooks/addon-jsx#60]
Hi there, thank you for making this wonderful addon for storybook, it has come in handy!

With this input:
```js
<div data={`{"bar"}`} />
```

I get this output in the addon:
```js
<div data="{&quot;bar&quot;}" />
```

Is it possible to display this the same way as the input? 

Thanks in advance!

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in v7.1.2 :rocket:
