### ISSUE TITLE
Unique "key" prop warning in v7.1.0

### ISSUE THREAD

**Issue by sheelah** [storybooks/addon-jsx#65]
Loving this addon, so thank for that!  I am noticing a warning in my browser console when I have this addon installed & enabled, and it disappears if I don't have this addon registered in my Storybook `addons.js`:

![Screen Shot 2019-04-08 at 11 26 08 AM](https://user-images.githubusercontent.com/1900318/55744037-25579d00-59f1-11e9-8889-807c9e83553f.jpg)

Looks like the warning is coming from Emotion, used by `@storybook/theming`.  I downgraded to v6 and still saw this warning.

**Comment by brandon-pereira** [comment]
I'm also getting this error.

**Comment by AddOneDn** [comment]
Same to me

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in v7.1.1 :rocket:
